spring:
  application:
    name: Cashflow Tracker Api
  datasource:
    url: jdbc:postgresql://localhost:5432/cashflow
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
     ddl-auto: update
    properties:
      hibernate.format_sql: true